---
title: "Makine Öğrenmesi"
author: 
  name: "Prof. Dr. Hüseyin Taştan"
  affiliation: "Yıldız Teknik Üniversitesi"
output: 
  html_document:
    theme: flatly
    highlight: haddock
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

İktisadi Analiz için Makine Öğrenmesi (YTU MP İktisat TYL) ders notları 

## Ders Planı


1. Giriş: [html](docs/Giris.html) | [pdf](docs/Giris.pdf)

2. Temel Kavramlar: [html](docs/Temel-Kavramlar.html) | [pdf](docs/Temel-Kavramlar.pdf)

3. R Programı 
    - R Base: <https://htastan.github.io/R-Giris/R-Base.html>
      - Repository: <https://github.com/htastan/R-Giris>
    - R Tidyverse: <https://htastan.github.io/R-Giris/R-Tidyverse.html>
      - Repository: <https://github.com/htastan/R-Giris> 
    - R Markdown Nedir: [html](R/RMarkdown.html) 
    - R Markdown Örnek: <https://htastan.github.io/RMarkdown-Ornek/RMarkdown_Ornek>
      - Repository: <https://github.com/htastan/RMarkdown-Ornek>
    - R Veri İndirme: <https://htastan.github.io/R-veri-indirme/R_veri_paketleri>
      - Repository: <https://github.com/htastan/R-veri-indirme>
<br/>
<br/>

4. Regresyon Problemleri
    - Sunum notları: [html](docs/Regresyon.html)  
    - Uygulamalar: [html](R/R-Regresyon.html) | [RMarkdown](R/R-Regresyon.Rmd)
<br/>
<br/>

5. Sınıflandırma Problemleri 
    - Sunum notları: [html](docs/Siniflandirma.html)  
    - Uygulamalar: [html](R/R-Siniflandirma.html) | [RMarkdown](R/R-Siniflandirma.Rmd)
<br/>
<br/>

6. Geçerleme Yöntemleri ve Bootstrap 
    - Sunum notları: [html](docs/Gecerleme.html)  
    - Uygulamalar: [html](R/R-Gecerleme.html) | [RMarkdown](R/R-Gecerleme.Rmd)
<br/>
<br/>

7. Model Seçimi ve Düzenlileştirme 
    - Sunum notları: [html](docs/Duzenlilestirme.html)  
    - Uygulamalar: [html](R/R-Duzenlilestirme.html) | [RMarkdown](R/R-Duzenlilestirme.Rmd)
<br/>
<br/>

8. Doğrusal Olmayan Yöntemler 
    - Sunum notları: [html](docs/Dogrusal-olmayan-modeller.html)  
    - Uygulamalar: [html](R/R-Dogrusal-olmayan-modeller.html) | [RMarkdown](R/R-Dogrusal-olmayan-modeller.Rmd) 
<br/>
<br/>

9. Ağaç Bazlı Yöntemler 
    - Sunum notları: [html](docs/Agac-bazli-yontemler.html)  
    - Uygulamalar: [html](R/R-Agac-bazli-yontemler.html) | [RMarkdown](R/R-Agac-bazli-yontemler.Rmd)  
<br/>
10. Gözetimsiz Öğrenme
    - Sunum notları: [html](docs/Gozetimsiz-Ogrenme.html)  
    - Uygulamalar: [html](R/R-Gozetimsiz-ogrenme.html) | [RMarkdown](R/R-Gozetimsiz-ogrenme.Rmd)   
<br/>
<br/>


